if(!require(XML)) install.packages("XML"); library(XML)
# espanya (Direccion General de Trafico)
datos <- xmlParse("http://infocar.dgt.es/datex2/dgt/SituationPublication/all/content.xml")
xml_datos <- xmlToList(datos)
# pais vasco (Direccion de Trafico del Gobierno Vasco)
datos2 <- xmlParse("http://infocar.dgt.es/datex2/dt-gv/SituationPublication/all/content.xml")
xml_datos2 <- xmlToList(datos2)
# catalunya (Servei Catala de transit)
datos3 <- xmlParse("http://infocar.dgt.es/datex2/sct/SituationPublication/all/content.xml")
xml_datos3 <- xmlToList(datos3)